apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "modeInstance/us-central1-a/filestore-demo-cluster-filestore/nfsshare"
    volumeAttributes:
      ip: "10.98.117.18"
      volume: "nfsshare"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: filestore-pv
  resources:
    requests:
      storage: 100Gi